### ISSUE TITLE
Replace SpecialResource dependency mechanism with Helm's

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/special-resource-operator#4]
Currently, a SpecialResource can depend on several dependencies, although only one level is supported.
To specify dependencies, the [`spec.dependencies`](https://github.com/openshift-psap/special-resource-operator/blob/master/api/v1beta1/specialresource_types.go#L126) field is used.
This feature seems to duplicate Helm's own dependency management system. Should we move to the Helm dependency management system and deprecate the existing one?

## Pros
- All existing features should be supported: values injection, any number of dependencies can be specified;
- SRO's dependency management code can be removed;
- Users do not have to create a SpecialResource instance for each dependency that they want to use.

## Cons
- Dependencies need to be downloaded and packaged together with the recipe. This can lead to issues when using SRO's ConfigMap Helm provider, as ConfigMaps can be up to 1MB in size;
- If a dependency needs to be updated, SRO will re-render the entire bundle (dependencies + recipe) and re-apply it all.

**Comment by zvonkok** [comment]
The order of execution for dependencies is not right. This will break our use-cases. 

1. Dependencies should be a standalone special-resource they should and can exits as a standalone deployment.
2. You have no control over how dependencies are executed. 
3. Some recipes create artifacts that are needed by other recipes and hence need to be reconciled first. 
4. ConfigMap is solely used for development and testing purposed not for production 
5. This is a very simplistic example where it looks "okay" but this can get ugly if you have a lot of parameters you want to tune in the CR

This is the biggest "no-go" `This means the resources are later on ordered by their kind, not their recipe`this breaks the whole point of SRO and independent helm charts.

**Comment by zvonkok** [comment]
> -  All existing features should be supported: values injection, any number of dependencies can be specified;

It was made intentionally only one level dependency to not complicate things, we do not need any number of dependency, so this is not really a "pro". 

> -  SRO's dependency management code can be removed;

Why? It is very simple if dependency then reconcile dependency else reconcile parent fi, reconcile parent


> - Users do not have to create a SpecialResource instance for each dependency that they want to use.

Dependencies should be fully qualified SpecialResources, because they might be used as a standalone deployment anyway.

**Comment by pacevedom** [comment]
> 1. Dependencies should be a standalone special-resource they should and can exits as a standalone deployment.

How does this play along with having 2 recipes with the same dependency, but different parameters? Or upgrades to the same dependency that might break other dependers? Wouldnt it require additional O&M procedures from the users perspective, since there are now more resources than initially handled?

> 2. You have no control over how dependencies are executed.
> 3. Some recipes create artifacts that are needed by other recipes and hence need to be reconciled first.

This is true, it is the only pain point of using helm. Still, can you post an example?

> 4. ConfigMap is solely used for development and testing purposed not for production

Then this is not a bad thing for using helm dependencies, right?

> 5. This is a very simplistic example where it looks "okay" but this can get ugly if you have a lot of parameters you want to tune in the CR

I have seen heavy customization of helm subcharts and its not so different with specifying parameters in different lists. Also, this might get ugly when having high levels of subcharting because of deep nesting. Still, aliasing should help make things clear/easier. To me this is more of a cosmetic thing in the yaml file layout.

> This is the biggest "no-go" `This means the resources are later on ordered by their kind, not their recipe`this breaks the whole point of SRO and independent helm charts.

Are they really independent?

> > * All existing features should be supported: values injection, any number of dependencies can be specified;
> 
> It was made intentionally only one level dependency to not complicate things, we do not need any number of dependency, so this is not really a "pro".

Then you would not have a complex subcharting customization, right?

> > * SRO's dependency management code can be removed;
> 
> Why? It is very simple if dependency then reconcile dependency else reconcile parent fi, reconcile parent

If we switch to helm dependencies then we dont really need to handle it in the source code. The question is whether helm dependencies are enough.

> > * Users do not have to create a SpecialResource instance for each dependency that they want to use.
> 
> Dependencies should be fully qualified SpecialResources, because they might be used as a standalone deployment anyway.

Can you elaborate this? For example, having `cert-manager` as a dependency should qualify as a `SpecialResource`, but it is not really a special resource, its just a dependency for my original/parent `SpecialResource`.

**Comment by zvonkok** [comment]
Some good points :) 

> How does this play along with having 2 recipes with the same dependency, but different parameters? Or upgrades to the same dependency that might break other dependers? Wouldnt it require additional O&M procedures from the users perspective, since there are now more resources than initially handled?

I think this is a higher level question and we need to answer this in general not on the implementation level. Those questions can be asked in the very same form to the helm-dependency solution. 

> This is true, it is the only pain point of using helm. Still, can you post an example?

There are e.g. build artifacts like kernel symbols or kernel sources that are needed by other recipes to build their kernel module because they need exported symbols from them. Those can only be built after the module is loaded and the sources with which they are built are made available. 

> Then this is not a bad thing for using helm dependencies, right?

I do not see how helm deps would help here rather than increase the size of the CM and may break with the 1MB limit.

> Are they really independent?

Yes depending on the use-case. If you want just to deploy the networking stack to enable NICs this is fine, if you want to do GPUDirect the networking stack becomes a dependency of the GPU and peer-mem stack. 

> Then you would not have a complex subcharting customization, right?

Indeed, flat hierarchy. 

> Can you elaborate this? For example, having cert-manager as a dependency should qualify as a SpecialResource, but it is not really a special resource, its just a dependency for my original/parent SpecialResource.

Good point, the prime example is GPUDirect which needs GPUs and NICs. If you're only interested in a high speed network then you would just deploy the NIC stack. If you want just GPUs you would deploy the GPU stack. If you want to do GPUDirect and you would deploy the GPU and NIC stack.

Then if you want to do GPU Direct storage this brings yet another level of dependency which needs GPUDirect. But all those parts aka dependencies can be used as a standalone deployment dependent on the use-case. 

The dep cert-manager is a good example of not really an SR but part of the enablement stack. 

I need to think more about this.

**Comment by pacevedom** [comment]
> Some good points :)
> 
> > How does this play along with having 2 recipes with the same dependency, but different parameters? Or upgrades to the same dependency that might break other dependers? Wouldnt it require additional O&M procedures from the users perspective, since there are now more resources than initially handled?
> 
> I think this is a higher level question and we need to answer this in general not on the implementation level. Those questions can be asked in the very same form to the helm-dependency solution.

Well, with helm dependencies you should be able to withstand that situation without changing anything. Dependencies get installed in the same namespace and with subcharting you can customize them right away.

It is true though that it depends on what you understand by dependency. If its another SpecialResource then I am not so sure about the approach, as you need to have cross-helm ordering and waiting. Or some sort of way to have SRO control the charts from each dependency, even if specified with helm. I will look into it, now that you mentioned it.

> > This is true, it is the only pain point of using helm. Still, can you post an example?
> 
> There are e.g. build artifacts like kernel symbols or kernel sources that are needed by other recipes to build their kernel module because they need exported symbols from them. Those can only be built after the module is loaded and the sources with which they are built are made available.

I see this as pure `SpecialResource` or maybe even `BuildConfig` (in case of OCP) dependencies. These require some special treatment indeed. Will look into how to handle this, if possible.

> > Then this is not a bad thing for using helm dependencies, right?
> 
> I do not see how helm deps would help here rather than increase the size of the CM and may break with the 1MB limit.

What I mean is that if we use helm dependencies (which include the charts as either tgz or yaml manifests) the CM size would increase, but if this is intended only for testing and dev then its not an issue. A helm registry should pose no problem.

> > Are they really independent?
> 
> Yes depending on the use-case. If you want just to deploy the networking stack to enable NICs this is fine, if you want to do GPUDirect the networking stack becomes a dependency of the GPU and peer-mem stack.

I see. And those dependencies would be SpecialResources themselves too, right? I mean, you need to build some kernel modules/drivers. The upgrade use case would require some attention when having these dependency relationships.

> > Then you would not have a complex subcharting customization, right?
> 
> Indeed, "flat hierarchy".

Then it looks to me as a cosmetic change/preference. Either have 2 `set` sections in different parts of the yaml, or have everything in the same place.

> > Can you elaborate this? For example, having cert-manager as a dependency should qualify as a SpecialResource, but it is not really a special resource, its just a dependency for my original/parent SpecialResource.
> 
> Good point, the prime example is GPUDirect which needs GPUs and NICs. If you're only interested in a high speed network then you would just deploy the NIC stack. If you want just GPUs you would deploy the GPU stack. If you want to do GPUDirect then you would deploy the GPU and NIC stack.
>
> Then if you want to do GPU Direct storage this brings yet another level of dependency which needs GPUDirect. But all those parts aka dependencies can be used as a standalone deployment dependent on the use-case.
> 
> The dep cert-manager is a good example of not really an SR but part of the enablement stack.

So this is the same use case than above, right? These look indeed like `SpecialResources` of their own to me. I mean, they are also dependencies, but they have their own rights to be a stand alone `SpecialResource`. I think I need to investigate a bit more into how we could handle this with helm dependencies.

I was thinking of dependencies as with the cert-manager, which is more of a separate piece of software that I need, not a full blown kernel module.

The upgrade use case, that's something to look into when having these relationships between SRs. Or even deploying more than once the same SR but with different configs.

> I need to think more about this.

Me too, but glad to discuss!

**Comment by zvonkok** [comment]
What about a hybrid approach. If the SR is not really an SR, do helm-deps otherwise do SR dependency?

**Comment by zvonkok** [comment]
> I see. And those dependencies would be SpecialResources themselves too, right? I mean, you need to build some kernel modules/drivers. The upgrade use case would require some attention when having these dependency relationships.

Yes and I currently do not see how you can solve that easy with helm-dependencies which would be far easier with SR deps because you have a clear dep chain and are in control of what gets deployed first and what not.

**Comment by zvonkok** [comment]
> The upgrade use case, that's something to look into when having these relationships between SRs. Or even deploying more than once the same SR but with different configs.

There is no guarantee or option that you can deploy SRs multiple times with different configs. Having SRs deps would prevent that because you would already have an SR instance of a specific chart. 

You cannot enable an HW accelerator or HW in general multiple times with different configs. One config and done.
