### ISSUE TITLE
Upgrade controller / notification mechanism

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/special-resource-operator#5]
SRO currently only notices upgrades when nodes with new kernels are joining the cluster. Because Kubernetes does not offer a standard upgrade facility or API, SRO cannot be notified in advance of upcoming upgrades, nor can it stop them in case it detects that there will be a problem with a SpecialResource it's managing.
Let us think of a system that would provide an abstract enough API for notifying the cluster that an upgrade is incoming or in progress. It would be up to Kubernetes vendors to implement that API.

@yevgeny-shnaidman @zvonkok please don't hesitate to elaborate your ideas in the comments.

**Comment by yevgeny-shnaidman** [comment]
I think that the idea @zvonkok put up yesterday makes more sense: not to have a dedicated API implemented somewhere in the code, but to have a dedicated controller that will be responsible for handling the upgrade flow. This controller will be responsible for:
1) determine if cluster is going to be upgraded/ is being upgraded
2) execute preflight checks ( as determined by the vendor
3) decide what to do in case it want to stop upgrade ( alert, pause upgrade, taint nodes etc')
By default, K8s will contain an empty controller, and each vendor will provide its own implementation
This  is is a much more flexible way then defining API, which we cannot be sure if they will be adaptable for all vendor, and especailly since step 1 involves getting the notifications,and not sending them

**Comment by zvonkok** [comment]
I think we need an update controller for SRO anyway. We talked about one upgrade path, but there are even more, an OpenShift upgrade e.g. hast two flavours, one where OCP aka the operators are updated and RHCOS is not and one where OCP and RHCOS is updated. In the first case there will be no reboot for RHCOS. 

Additionally how are we going to handle the following use-cases:

1. Upgrade of SRO
2. Upgrade of a single recipe ( We need to check if the new driver works on the old kernel) 
3. Upgrade a recipe with dependencies 

Preflight checks need to involve check-in a new driver on an old kernel, and old driver on a new kernel. 

5.

**Comment by yevgeny-shnaidman** [comment]
> I think we need an update controller for SRO anyway. We talked about one upgrade path, but there are even more, an OpenShift upgrade e.g. hast two flavours, one where OCP aka the operators are updated and RHCOS is not and one where OCP and RHCOS is updated. In the first case there will be no reboot for RHCOS.
> 
> Additionally how are we going to handle the following use-cases:
> 
> 1. Upgrade of SRO
I think this must be solved by the actual new code in the SRO. In most of the cases i see no issue with upgrading SRO, but in case a new code introduces some major change in handling the CRs (or even a change in the API), then this version should also contain a migration code
> 2. Upgrade of a single recipe ( We need to check if the new driver works on the old kernel)
What is the difference between updating a CR and adding a new CR? i don't think that this is an upgrade path (it will not be handled by the upgrade controller), but a regular CR handling path. Do we want to start verifying kernel compliance also for a new CRs?
> 3. Upgrade a recipe with dependencies
At least for now, it seems that any changes that will be added for the previous 2 points, will solve the handling of the recipes with dependencies.
> 
> Preflight checks need to involve check-in a new driver on an old kernel, and old driver on a new kernel.
> 
> One thing to keep in mind we're here to solve the case for vanilla k8s and not only for OCP especially.

I think we need to consolidate what actions (preflight checks) we execute during upgrade kernel flow, and what actions (preflight checks, if any we execute during normal flow of handling the CR

Since in the K8s flow, the DTK will be provided by the vendor, i think that we need to start defining the requirements for the DTK images. for example, that they should contain a predefined file with the supported kernel version, that will allow us to execute some of the preflight checks.
We also need to figure out what is needed for Buildconfig verification

**Comment by qbarrand** [comment]
> for example, that they should contain a predefined file with the supported kernel version, that will allow us to execute some of the preflight checks

Or maybe an [image label](https://docs.docker.com/config/labels-custom-metadata/).

**Comment by yevgeny-shnaidman** [comment]
> > for example, that they should contain a predefined file with the supported kernel version, that will allow us to execute some of the preflight checks
> 
> Or maybe an [image label](https://docs.docker.com/config/labels-custom-metadata/).

agree regarding image labels. We just need to agree on an easily implementable format
